### ISSUE TITLE
Launchbox Bigbox crashes on game exit with steamlauncher enabled

### ISSUE THREAD

**Issue by wiesshund** [lahma0/SteamLauncher#2]
Launches just fine, game playes, does not matter what type of game.
On return to LB or BB, they just crash to desktop.

Disabling steamlauncher prevents the crash.

Does not seem to get trapped in the log file though
looks same on game exit with or without steam launcher :(
[Debug 2024-11-12 12-30-53 PM.log](https://github.com/user-attachments/files/17720896/Debug.2024-11-12.12-30-53.PM.log)

**Comment by wiesshund** [comment]
[debug.log](https://github.com/user-attachments/files/17720932/debug.log)

**Comment by lahma0** [comment]
I will try to look at this as soon as I can. I'm super slammed right now,
but I should have a chance to look at it over the holidays sometime.

**Comment by wiesshund** [comment]
Wont you be busy
Eating?

LoL

For now i just put launchbox on a loop
if the process vanishes, it relaunches it

Wonder what steam changed now?

**Comment by wiesshund** [comment]
Wonder what the bugger this is on about.
It repeats in the LB startup log.
DLL referenced is not and hasn't been present in any steam launcher version i have.
Not sure this means anything but


`2024-11-24 01:24:39 PM Resolving assembly SteamLauncher.XmlSerializers, Version=0.9.8.5, Culture=neutral, PublicKeyToken=null, processorArchitecture=AMD64...
2024-11-24 01:24:39 PM FIRST CHANCE EXCEPTION: Could not load file or assembly 'SteamLauncher.XmlSerializers, Version=0.9.8.5, Culture=neutral, PublicKeyToken=null, processorArchitecture=AMD64'. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
2024-11-24 01:24:40 PM FIRST CHANCE EXCEPTION: Could not load file or assembly 'D:\Emulation\LaunchBox\Core\SteamLauncher.XmlSerializers.dll'. The system cannot find the file specified.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
2024-11-24 01:24:40 PM Resolving assembly SteamLauncher.XmlSerializers, Version=0.9.8.5, Culture=neutral, PublicKeyToken=null, processorArchitecture=AMD64...
2024-11-24 01:24:40 PM FIRST CHANCE EXCEPTION: Could not load file or assembly 'SteamLauncher.XmlSerializers, Version=0.9.8.5, Culture=neutral, PublicKeyToken=null, processorArchitecture=AMD64'. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
2024-11-24 01:24:40 PM FIRST CHANCE EXCEPTION: Could not load file or assembly 'D:\Emulation\LaunchBox\Core\SteamLauncher.XmlSerializers.dll'. The system cannot find the file specified.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
2024-11-24 01:24:40 PM Resolving assembly SteamLauncher.XmlSerializers, Version=0.9.8.5, Culture=neutral, PublicKeyToken=null, processorArchitecture=AMD64...
2024-11-24 01:24:40 PM FIRST CHANCE EXCEPTION: Could not load file or assembly 'SteamLauncher.XmlSerializers, Version=0.9.8.5, Culture=neutral, PublicKeyToken=null, processorArchitecture=AMD64'. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
2024-11-24 01:24:40 PM FIRST CHANCE EXCEPTION: Could not load file or assembly 'D:\Emulation\LaunchBox\Core\SteamLauncher.XmlSerializers.dll'. The system cannot find the file specified.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)`

**Comment by wiesshund** [comment]
Nevermind, i learned that the above is just a known thing with the MS debugger
It spits blah.xml.serializer errors out, when there is no error and all is fine

**Comment by wiesshund** [comment]
I gave it a stab at trying to figure out the cause and help out, but unfortunately i got nothing to offer.
Software dev not my forte.

Anyways happy Thanksgiving

**Comment by wiesshund** [comment]
any luck so far?
